### ISSUE TITLE
Modifiers being ignored

### ISSUE THREAD

**Issue by amirkhan81** [jamiepollock/umbraco-grid-settings#1]
With the default properties you can use a modifier to describe the property / add a hook for CSS, this doesn't seem to work as expected with the color picker property? Below just outputs the hex value instead of grid-row-scheme-value.

 {
    "label": "Background Color",
    "description": "Select the background color scheme you want for this row",
    "key": "class1",
    "view": "/App_Plugins/Our.Umbraco.GridSettings/editors/ColorPicker/view.html",
    "prevalues": [
      {
        "label": "Blue",
        "value": "#0000ff"
      },
      {
        "label": "Green",
        "value": "#00ff00"
      }
    ],
    "modifier": "grid-row-scheme-{0}"
  },

**Comment by jamiepollock** [comment]
Hey @amirkhan81, thanks for testing out Grid Settings! I'm sorry, I don't quite understand your issue.

are you expecting it to output `grid-row-scheme-Green` or `grid-row-scheme-Blue`? But instead you're getting `grid-row-scheme-#00ff00` and `grid-row-scheme-#0000ff`?

**Comment by amirkhan81** [comment]
Hi @jamiepollock, great package and thanks for the reply. Its actually just outputting #0000FF,  ignoring the grid-row-scheme all together. Though ideally I'd like grid-row-scheme-green so its cleaner to target with CSS.

**Comment by jamiepollock** [comment]
@amirkhan81 Thanks! :) Interesting. Is this a setting or a style property? I'm thinking this is standard Umbraco behaviour as all this package is doing is providing a means for authors to add values.

**Comment by amirkhan81** [comment]
@jamiepollock It is a settings property. You could be right. The below however works as expected, maybe something with the new ability to add both a label and a value.

 {
    "label": "Background Color",
    "description": "Select the background color you want for this row",
    "key": "class1",
    "applyTo": "row",
    "view": "radiobuttonlist",
    "prevalues": [
      "none",
      "red",
      "blue",
      "gray-light",
      "gray-medium",
      "gray-darnk"
    ],
    "modifier": "grid-row-scheme-{0}"
  },

**Comment by jamiepollock** [comment]
Also sadly the current version does not support the label value as something passed as a saved value. It's simply there for display purposes.

However I can see the need for wanting to add this in. I don't have a solution at this time but I'll keep this in mind for a future update. I believe any changes to the current colour picker in how values are saved would lead to a breaking change. So a new color picker which supported classes would end up being a new property editor.

**Comment by jamiepollock** [comment]
@amirkhan81 hmm, I see. Could be the #? clutching at straws here. I'll see about adding in a colour picker which supports classes in the next update. That should be in the next couple of days as I'm working on some DevOps work right now.

**Comment by amirkhan81** [comment]
@jamiepollock Awesome! Ping me if you need any help!

**Comment by jamiepollock** [comment]
Hey @amirkhan81, I have some time to work on this today. How are you using this package? I only ask because I'll have some build artifacts over on AppVeyor soon.

**Comment by amirkhan81** [comment]
Hi @jamiepollock , I'm using it to add a background color datatype in the grid editor settings JSON. Nothing fancy. Umbraco version 7.5.11. Top of the thread is the exact JSON I was using which is outputting in the class of the row "#ffffff" for example, we do have a way of rendering the classes that isn't standard to allow multiple classes, info on that here: https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/60368-Grid-Settings-PreValueEditors

And attached is our view to render the grid.

**Comment by amirkhan81** [comment]
[Content.txt](https://github.com/jamiepollock/umbraco-grid-settings/files/902884/Content.txt)

**Comment by jamiepollock** [comment]
Ahh, that's good to know. Sorry I meant to ask are using the nuget or Umbraco Package zip file?

**Comment by amirkhan81** [comment]
Ah sorry, Package Zip file.

**Comment by jamiepollock** [comment]
No worries! My question wasn't clear. I'll have a package zip ready for you in a bit. Should be ready in the next half an hour.

**Comment by amirkhan81** [comment]
Awesome, in meetings for the next 2ish hours. just didn't want to leave you waiting for feedback.

**Comment by jamiepollock** [comment]
@amirkhan81 appreciate it :)

**Comment by jamiepollock** [comment]
@amirkhan81 okay, you can find the latest build with the new "Class Color Picker" over on [Appveyor](https://ci.appveyor.com/project/jamiepollock/umbraco-grid-settings/build/artifacts).

Also [usage documentation here](https://github.com/jamiepollock/umbraco-grid-settings/blob/develop/docs/Usage.md#class-color-picker)!

You're going to need to change your editor view path from ColorPicker to ClassColorPicker and reverse the key value pairs. As noted in the docs string values won't work any more as we're going to need both the label & value values.

Let me know what you think! Also from what I could see, yep there's an issue with multiple values for a class but at least you have a picker now to provide a class nicely :)

**Comment by amirkhan81** [comment]
Confirming this works as expected!

That grid view I sent you btw is a handy fix for the class issue you can assign as many as you want as long as the key is class+somethingunique.

Thanks again!

**Comment by jamiepollock** [comment]
@amirkhan81 awesome :) yea, I'm thinking about putting a helper class in at some point to help with classes like this.

I'll have an "official" release on Our Umbraco tomorrow but it'll be exactly the same code just versioned differently. Thanks for introducing a new bit of functionality to this package :)

Can I close this ticket now?

**Comment by amirkhan81** [comment]
Sounds great.

Yes you can close the ticket. thank you!
-- 

Amir Khan
Black Swan Interactive 

1802 Perrysburg Holland Rd
Holland, Ohio 43528 USA


t:   +1.567.343.2255 <> <tel:%2B1.567.343.2255 <>> 
m: +1.614.354.8672 <> <tel:%2B1.614.354.8672 <>> 
e: amir@blackswaninteractive.com <http://amir@blackswaninteractive.com/>

**Comment by jamiepollock** [comment]
Hey @amirkhan81, in case you missed it. This release is now live and available on the [releases section](https://github.com/jamiepollock/umbraco-grid-settings/releases/tag/v0.2.0) and also [Our Umbraco](https://our.umbraco.org/projects/backoffice-extensions/grid-settings/). :)

I've given you a nod as thanks for your support on this new addition.

Thanks again!
