### ISSUE TITLE
Feature Request - Toggle / Deselect Values

### ISSUE THREAD

**Issue by McGlade** [jamiepollock/umbraco-grid-settings#2]
Hi Jamie, 
Great package. Really like it. 
It would be nice though to be able to deselect the property values.

Martin.

**Comment by jamiepollock** [comment]
@McGlade Great suggestion. I was actually thinking of adding that in for v0.1.0 but didn't get around to it.

I'll have a think about adding this in.

**Comment by jamiepollock** [comment]
@McGlade I've added in this functionality now to all property editors. Could you check out the artifacts available over on AppVeyor and give it a try?

This includes a nuget package and the Umbraco package which can be installed locally.

https://ci.appveyor.com/project/jamiepollock/umbraco-grid-settings/build/artifacts

**Comment by jamiepollock** [comment]
@McGlade I've included this and other features in the v0.3.0-beta. Available on [Our Umbraco](https://our.umbraco.org/projects/backoffice-extensions/grid-settings/) and [NuGet](https://www.nuget.org/packages/Our.Umbraco.GridSettings/0.3.0-beta).

**Comment by McGlade** [comment]
@jamiepollock, looks good to me. Thanks.

**Comment by jamiepollock** [comment]
@McGlade great. I'll close this ticket then. Thanks for your feedback, it's really improved the Grid Settings package.

**Comment by tompipe** [comment]
Heh - I just came to report this issue too. Glad it's been fixed 👍
